#!/usr/bin/env bash
#receives a parameter to do an action, initialize another script running in backgroung or daemon

DIR="/tmp"
FILE="$DIR/my_process.pid"
MSG="manage_my_process"

start_pro(){
	./manage_my_process &
	mkdir -p "$DIR"
	touch "$FILE"
	echo "$!" > "$FILE"
}

stop_pro(){
	kill "$(cat "$FILE")"
	rm "$FILE"
}

restart_pro(){
	stop_pro
	start_pro
}

case "$1" in
	start)
		start_pro
		echo "$MSG started"
		;;
	stop)
		stop_pro
		echo "$MSG stopped"
		;;
	restart)
		restart_pro
		echo "$MSG restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
esac
