#!/usr/bin/env bash
#receives a parameter to do an action, initialize another script running in backgroung or daemon

# ./tmp   and tmp problem at my kali

DIR="/tmp"
FILE="$DIR/my_process.pid"
MSG="manage_my_process"

start_pro(){
	./manage_my_process &
	mkdir -p "$DIR"
	touch "$FILE"
	echo $! > "$FILE"
}

stop_pro(){
	kill $(cat "$FILE")
	rm  "$FILE"
}

restart_pro(){
	stop_pro
	start_pro
}

#trap 'stop; exit 0' TERM INT QUIT   #not necessary because this processes closes directly

case "$1" in
	start)
		start_pro
		echo "$MSG started"
		;;
	stop)
		echo "$MSG stopped"
		stop_pro
		;;
	restart)
		echo "$MSG restarted"
		restart_pro
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
