#!/usr/bin/env bash
#scrip to loop a comment, and to comment depending the received signal
#creats a folder and a file inside with a PID process identification
DIR="tmp"
FILE="$DIR/myscript.pid"
mkdir -p "$DIR"
touch "$FILE"
chmod +w "$FILE"
echo $$ > "$FILE"

cleanup_term(){
	echo "I hate the kill command"
	rm -f "$FILE"
	exit 0
}

cleanup_quit(){
	rm -f "$FILE"
	exit 0
}

trap 'cleanup_term' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup_quit' SIGQUIT

while (true)
do 
        echo 'To infinity and beyond indefinitely'
        sleep 2
done

