#!/usr/bin/env bash
#scrip to loop a comment, and to comment depending the received signal
#creats a folder and a file inside with a PID process identification
DIR="/tmp"
FILE="$DIR/myscript.pid"
mkdir -p "$DIR"
touch "$FILE"
chmod +w "$FILE"
echo $$ > "$FILE"

cleanup_term(){
	echo "I hate the kill command"
	rm -f "$FILE"
	exit 0
}

cleanup_quit(){
	rm -f "$FILE"
	exit 0
}

trap cleanup_term TERM
trap 'echo "Y U no love me?!"' INT
trap cleanup_quit QUIT

while true
do 
        echo 'To infinity and beyond indefinitely'
        sleep 2
done

